name: Run E2E tests

on:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        env:
          NEXT_PUBLIC_API_BASE_URL: "https://devstore-backend-rho.vercel.app"
          APP_URL: "http://localhost:3000"
        with:
          working-directory: frontend
          build: npm run build
          start: npm start
